import Head from "next/head";
import { MdOutlineLocalPhone } from "react-icons/md";
import { CgProfile } from "react-icons/cg";
import Image from "next/image";
import { useState } from "react";
import Link from "next/link";

export default function Home() {
  const [form, setForm] = useState({
    name: "",
    phoneNumber: "",
  });

  const [consent, setConsent] = useState(true);

  const changeHandler = (e) => {
    e.target.name == "name"
      ? setForm({
          ...form,
          [e.target.name]: e.target.value
            .replace(/[0-9]/, "")
            .replace(/[^a-z]/gi, " "),
        })
      : setForm({
          ...form,
          [e.target.name]: e.target.value.replace(/\D/g, ""),
        });
  };

  const formHandler = (e) => {
    const requestOptions = {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(form),
    };
    e.preventDefault();
    // inside fetch put api link
    fetch("", requestOptions)
      .then((response) => response.json())
      .then((data) => console.log(data));
  };

  return (
    <div>
      <Head>
        <title>Apnapaisa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <nav className="navbar bg-light">
          <div className="container-fluid">
            <a className="navbar-brand" href="#">
              <img src="logo.svg" alt="" />
            </a>
          </div>
        </nav>
        <div className="row mt-4 mx-3">
          <div className="col-12 col-md-6 px-0 px-md-5">
            <div className="mt-1 pt-1 mt-lg-5 pt-lg-5 d-flex flex-column justify-content-center">
              <h1 className="display-4 fw-bold">
                Your Credit Score is just a click away.
              </h1>
              <p className="display-6 fs-5 mt-2">
                A good credit score can help you get the best rates on loans. It
                can also help you get a new credit card with great deals and
                offers.
              </p>
            </div>
          </div>

          <div className="col-12 col-md-6 d-flex justify-content-center px-0 px-md-5 ">
            <form className="border border-primary rounded p-3 px-md-5 mt-4 mt-md-0 mb-5 mb-md-5 form">
              <div className="">
                <label className="form-label mt-2" htmlFor="name">
                  Full Name*
                </label>
                <div className="input-group">
                  <input
                    required
                    className="form-control"
                    type="text"
                    name="name"
                    id="name"
                    placeholder="Full Name"
                    value={form.name}
                    onChange={(e) => changeHandler(e)}
                  />
                  <span className="input-group-text">
                    <CgProfile />
                  </span>
                </div>
              </div>
              <div className="">
                <label
                  className="form-label mt-4 mt-md-5"
                  htmlFor="phoneNumber"
                >
                  Phone Number*
                </label>
                <div className="input-group">
                  <span className="input-group-text">91+</span>
                  <input
                    required
                    className="form-control"
                    type="text"
                    name="phoneNumber"
                    id="phoneNumber"
                    placeholder="Mobile Number"
                    minLength={10}
                    maxLength={10}
                    value={form.phoneNumber}
                    onChange={(e) => changeHandler(e)}
                  />
                  <span className="input-group-text">
                    <MdOutlineLocalPhone />
                  </span>
                </div>
              </div>

              <div className="mb-3 form-check mt-4 mt-md-5">
                <input
                  type="checkbox"
                  className="form-check-input"
                  id="consent "
                  checked={consent}
                  onChange={() => setConsent(!consent)}
                />
                <label
                  className="form-check-label"
                  htmlFor="consent "
                  style={{ fontSize: "10px" }}
                >
                  *I agree to the{" "}
                  <Link
                    className="link-decoration"
                    href="https://apnadhan.com/privacy-policy"
                  >
                    Privacy Policy
                  </Link>{" "}
                  and{" "}
                  <Link
                    className="link-decoration"
                    href="https://apnadhan.com/terms-of-use"
                  >
                    Terms of use
                  </Link>{" "}
                  and hereby appoint the website as my authorised representative
                  to receive my credit information from CIBIL/ Equifax/
                  Experian/ CRIF.
                </label>
              </div>

              <div className="d-flex justify-content-center">
                <button
                  type="submit"
                  className="btn btn-primary"
                  style={{ border: "none" }}
                >
                  SUBMIT
                </button>
              </div>
            </form>
          </div>
        </div>
      </main>
    </div>
  );
}
